### ISSUE TITLE
15计科1-朱彬彬

### ISSUE THREAD

**Issue by enjoy-binbin** [huashangxueyuan/hackathon_exercise_3#2]
Baidu-index-withCss：
https://github.com/enjoy-binbin/enjoy-binbin.github.io/tree/master/baidu_demo_withCss
演示地址：
https://enjoy-binbin.github.io/baidu_demo_withCss/

咦，老师我想问下现在在前端中用的缩进是，tab还是spaces，哪个会更加规范些

**Comment by zhuayu** [comment]
tab 和 spaces 的规范中，在不同公司有不同的要求，没有前后端之分，主要是公司规范而定。例如 AfterShip 它家就是用 tab 的规范，而大多数都用 spaces 。在使用 spaces 缩进中，缩进几个格子不同公司又不一样，国内小公司的喜欢 4格，大厂及国外的公司例如 Google 喜欢 2 格。由于我接触的项目比较多，所以在不同的项目中就使用不同的规范切换，在自己的项目中，我偏向于 spaces 2 格缩进，因为在 Linux 中使用 cat 或者 vim 的时候会比较方便，同时上传到代码托管也方便查看。
